/* eslint-disable @typescript-eslint/no-explicit-any -- PostgreSQL rows and validated domain inputs are dynamically shaped at this data-access boundary. */
import { createHmac, randomBytes, randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import { getPool } from "@/server/db/pool";
import { getEnvironment } from "@/server/env";
import { decryptSensitive, encryptSensitive } from "@/server/security/encryption";

export type Session = { userId: string; profileId: string; sessionId: string };
export type CaseAccess = { role: "owner" | "advocate"; permissions: string[] };
const enc = (value: string | undefined, purpose: string) => value ? encryptSensitive(value, purpose) : null;

async function audit(client: PoolClient, actorId: string, eventType: string, resourceType: string, resourceId: string, metadata: Record<string, unknown> = {}) {
  await client.query("INSERT INTO audit_events (id,actor_id,event_type,resource_type,resource_id,metadata) VALUES ($1,$2,$3,$4,$5,$6)",[randomUUID(),actorId,eventType,resourceType,resourceId,metadata]);
}

export async function checkCaseAccess(session: Session, caseId: string, permission = "view_summary"): Promise<CaseAccess | null> {
  const owner = await getPool().query("SELECT 1 FROM cases WHERE id=$1 AND owner_user_id=$2 AND archived_at IS NULL",[caseId,session.userId]);
  if (owner.rowCount) return { role:"owner", permissions:["owner"] };
  const grant = await getPool().query<{permission:string}>(`SELECT p.permission FROM case_access_grants g JOIN cases c ON c.id=g.case_id AND c.archived_at IS NULL JOIN case_access_permissions p ON p.grant_id=g.id
    WHERE g.case_id=$1 AND g.grantee_user_id=$2 AND g.starts_at<=now() AND g.expires_at>now() AND g.revoked_at IS NULL AND g.suspended_at IS NULL AND p.permission=$3`,[caseId,session.userId,permission]);
  return grant.rowCount ? { role:"advocate", permissions:grant.rows.map((row)=>row.permission) } : null;
}

export async function listCases(session: Session) {
  const result=await getPool().query<{id:string;reference:string;title_encrypted:string;case_type:string;status:string;urgency:string;updated_at:Date;role:string}>(`SELECT c.id,c.reference,c.title_encrypted,c.case_type,c.status,c.urgency,c.updated_at,
    CASE WHEN c.owner_user_id=$1 THEN 'owner' ELSE 'advocate' END role FROM cases c
    WHERE c.archived_at IS NULL AND (c.owner_user_id=$1 OR EXISTS (
      SELECT 1 FROM case_access_grants g JOIN case_access_permissions p ON p.grant_id=g.id
      WHERE g.case_id=c.id AND g.grantee_user_id=$1 AND g.starts_at<=now() AND g.expires_at>now()
        AND g.revoked_at IS NULL AND g.suspended_at IS NULL AND p.permission='view_summary'
    )) ORDER BY c.updated_at DESC`,[session.userId]);
  return result.rows.map((row)=>({...row,title:decryptSensitive(row.title_encrypted,`case-title:${row.id}`),title_encrypted:undefined}));
}

export async function createCase(session: Session, input: {title:string;caseType:string;urgency:string;councilExternalId?:string;currentArea?:string;safeContact:boolean;discreetMode:boolean;accessibilityNeeds?:string}) {
  const id=randomUUID(), reference=`KHN-${new Date().getUTCFullYear()}-${randomBytes(4).toString("hex").toUpperCase()}`;
  const client=await getPool().connect(); try { await client.query("BEGIN");
    await client.query(`INSERT INTO cases (id,reference,owner_user_id,title_encrypted,case_type,status,urgency,council_external_id,current_area,safe_contact,discreet_mode,accessibility_needs_encrypted)
      VALUES ($1,$2,$3,$4,$5,'active',$6,$7,$8,$9,$10,$11)`,[id,reference,session.userId,encryptSensitive(input.title,`case-title:${id}`),input.caseType,input.urgency,input.councilExternalId??null,input.currentArea??null,input.safeContact,input.discreetMode,enc(input.accessibilityNeeds,`case-accessibility:${id}`)]);
    await audit(client,session.userId,"case.created","case",id,{caseType:input.caseType}); await client.query("COMMIT"); return {id,reference};
  } catch(error){await client.query("ROLLBACK");throw error} finally{client.release()}
}

export async function updateCase(session:Session,caseId:string,input:any){const access=await checkCaseAccess(session,caseId);if(access?.role!=="owner")return null;const current=await getPool().query<any>("SELECT title_encrypted FROM cases WHERE id=$1 AND owner_user_id=$2",[caseId,session.userId]);if(!current.rowCount)return null;const values:any[]=[caseId,session.userId],sets:string[]=[];const add=(column:string,value:any)=>{values.push(value);sets.push(`${column}=$${values.length}`)};if(input.title)add("title_encrypted",encryptSensitive(input.title,`case-title:${caseId}`));if(input.status){add("status",input.status);if(input.status==="archived")sets.push("archived_at=now()");if(input.status==="closed")sets.push("closed_at=coalesce(closed_at,now())")}if(input.urgency)add("urgency",input.urgency);if(input.currentArea!==undefined)add("current_area",input.currentArea);if(input.currentDuty!==undefined)add("current_duty",input.currentDuty);if(input.homelessnessStage!==undefined)add("homelessness_stage",input.homelessnessStage);if(input.primaryDeadline!==undefined)add("primary_deadline",input.primaryDeadline);sets.push("updated_at=now()");await getPool().query(`UPDATE cases SET ${sets.join(",")} WHERE id=$1 AND owner_user_id=$2`,values);await getPool().query("INSERT INTO audit_events (id,actor_id,event_type,resource_type,resource_id,metadata) VALUES ($1,$2,'case.updated','case',$3,$4)",[randomUUID(),session.userId,caseId,{fields:Object.keys(input)}]);return{id:caseId}}

export async function getCase(session: Session, caseId: string) {
  const access=await checkCaseAccess(session,caseId); if(!access)return null;
  const result=await getPool().query<any>("SELECT * FROM cases WHERE id=$1",[caseId]); const row=result.rows[0]; if(!row)return null;
  const [events,deadlines,applications,duties,evidence,people]=await Promise.all([
    access.role==="owner"||await checkCaseAccess(session,caseId,"view_timeline")?getPool().query("SELECT id,event_at,event_type,organisation,description_encrypted,privacy_classification,source FROM case_events WHERE case_id=$1 ORDER BY event_at DESC LIMIT 20",[caseId]):Promise.resolve({rows:[]}),
    access.role==="owner"||await checkCaseAccess(session,caseId,"view_deadlines")?getPool().query("SELECT id,title,due_at,deadline_status,confidence,completed_at FROM case_deadlines WHERE case_id=$1 ORDER BY due_at LIMIT 20",[caseId]):Promise.resolve({rows:[]}),
    getPool().query("SELECT id,kind,destination,status,follow_up_at FROM case_applications WHERE case_id=$1 ORDER BY updated_at DESC LIMIT 20",[caseId]),
    getPool().query("SELECT id,duty_type,start_date,legal_status,review_deadline FROM case_duties WHERE case_id=$1 ORDER BY created_at DESC LIMIT 20",[caseId]),
    access.role==="owner"||await checkCaseAccess(session,caseId,"view_evidence")?getPool().query("SELECT id,title_encrypted,category,sensitivity,storage_state,malware_scan_status,created_at FROM case_evidence WHERE case_id=$1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 20",[caseId]):Promise.resolve({rows:[]}),
    access.role==="owner"?getPool().query("SELECT g.id,g.grantee_user_id,g.expires_at,g.revoked_at,g.last_accessed_at,array_remove(array_agg(p.permission),NULL) permissions FROM case_access_grants g LEFT JOIN case_access_permissions p ON p.grant_id=g.id WHERE g.case_id=$1 GROUP BY g.id",[caseId]):Promise.resolve({rows:[]})
  ]);
  await getPool().query("INSERT INTO audit_events (id,actor_id,event_type,resource_type,resource_id,metadata) VALUES ($1,$2,'case.viewed','case',$3,$4)",[randomUUID(),session.userId,caseId,{role:access.role}]);
  return {id:row.id,reference:row.reference,title:decryptSensitive(row.title_encrypted,`case-title:${caseId}`),caseType:row.case_type,status:row.status,urgency:row.urgency,currentArea:row.current_area,currentDuty:row.current_duty,homelessnessStage:row.homelessness_stage,primaryDeadline:row.primary_deadline,role:access.role,
    events:events.rows.map((e:any)=>({...e,description:decryptSensitive(e.description_encrypted,`case-event:${e.id}:description`),description_encrypted:undefined})),deadlines:deadlines.rows,applications:applications.rows,duties:duties.rows,
    evidence:evidence.rows.map((e:any)=>({...e,title:decryptSensitive(e.title_encrypted,`case-evidence:${e.id}:title`),title_encrypted:undefined})),people:people.rows};
}

export async function addEvent(session:Session,caseId:string,input:any){if(!await checkCaseAccess(session,caseId,"add_notes"))return null;const id=randomUUID();const client=await getPool().connect();try{await client.query("BEGIN");await client.query(`INSERT INTO case_events (id,case_id,event_at,event_type,organisation,person_contacted,contact_method,description_encrypted,outcome_encrypted,reference_number_encrypted,follow_up_action_encrypted,deadline_at,privacy_classification,source,created_by,approved_by_user_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'user',$14,now())`,[id,caseId,input.eventAt,input.eventType,input.organisation??null,input.personContacted??null,input.contactMethod??null,encryptSensitive(input.description,`case-event:${id}:description`),enc(input.outcome,`case-event:${id}:outcome`),enc(input.referenceNumber,`case-event:${id}:reference`),enc(input.followUpAction,`case-event:${id}:follow-up`),input.deadlineAt??null,input.privacyClassification,session.userId]);await audit(client,session.userId,"case.event_added","case_event",id,{caseId,eventType:input.eventType});await client.query("COMMIT");return{id}}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}

export async function addDeadline(session:Session,caseId:string,input:any){if(!await checkCaseAccess(session,caseId,"complete_tasks"))return null;const id=randomUUID();await getPool().query(`INSERT INTO case_deadlines (id,case_id,title,due_at,source,deadline_status,confidence,consequence_encrypted,calculation_rule,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,caseId,input.title,input.dueAt,input.source,input.deadlineStatus,input.confidence,enc(input.consequence,`case-deadline:${id}:consequence`),input.calculationRule??null,session.userId]);await getPool().query("INSERT INTO audit_events (id,actor_id,event_type,resource_type,resource_id,metadata) VALUES ($1,$2,'case.deadline_added','case_deadline',$3,$4)",[randomUUID(),session.userId,id,{caseId,deadlineStatus:input.deadlineStatus}]);return{id}}
export async function addApplication(session:Session,caseId:string,input:any){if(!await checkCaseAccess(session,caseId,"prepare_letters"))return null;const id=randomUUID();await getPool().query(`INSERT INTO case_applications (id,case_id,kind,destination,status,reference_number_encrypted,shared_fields,submission_manifest) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,[id,caseId,input.kind,input.destination,input.status,enc(input.referenceNumber,`case-application:${id}:reference`),input.sharedFields,{fields:input.sharedFields,evidenceIds:[],reviewed:false}]);return{id}}
export async function addDuty(session:Session,caseId:string,input:any){if(!await checkCaseAccess(session,caseId,"add_notes"))return null;const id=randomUUID();await getPool().query(`INSERT INTO case_duties (id,case_id,duty_type,start_date,council_external_id,legal_status,notes_encrypted,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,[id,caseId,input.dutyType,input.startDate??null,input.councilExternalId??null,input.legalStatus,enc(input.notes,`case-duty:${id}:notes`),session.userId]);return{id}}
export async function addEvidenceMetadata(session:Session,caseId:string,input:any){if(!await checkCaseAccess(session,caseId,"upload_evidence"))return null;const id=randomUUID();await getPool().query(`INSERT INTO case_evidence (id,case_id,title_encrypted,category,description_encrypted,sensitivity,uploaded_by) VALUES ($1,$2,$3,$4,$5,$6,$7)`,[id,caseId,encryptSensitive(input.title,`case-evidence:${id}:title`),input.category,enc(input.description,`case-evidence:${id}:description`),input.sensitivity,session.userId]);await getPool().query("INSERT INTO audit_events (id,actor_id,event_type,resource_type,resource_id,metadata) VALUES ($1,$2,'evidence.metadata_created','case_evidence',$3,$4)",[randomUUID(),session.userId,id,{caseId,storageState:"blocked_pending_gate"}]);return{id,storageState:"blocked_pending_gate"}}

export function hashInvite(value:string){return createHmac("sha256",getEnvironment().SESSION_SECRET??"unconfigured").update(value).digest("hex")}
export async function createInvitation(session:Session,input:any){const access=await checkCaseAccess(session,input.caseId);if(access?.role!=="owner")return null;const id=randomUUID(),consentId=randomUUID(),token=randomBytes(32).toString("base64url"),email=input.email.trim().toLowerCase();const client=await getPool().connect();try{await client.query("BEGIN");await client.query(`INSERT INTO case_consents (id,case_id,owner_user_id,recipient,purpose,field_keys,permitted_actions,starts_at,expires_at) VALUES ($1,$2,$3,$4,'Advocate access invitation',ARRAY[]::text[],$5,$6,$7)`,[consentId,input.caseId,session.userId,email,input.permissions,new Date().toISOString(),input.expiresAt]);await client.query(`INSERT INTO advocate_invitations (id,case_id,invited_by,invitee_email_hash,invitee_email_encrypted,helper_type,token_hash,expires_at,requested_permissions,requested_sensitive_categories,consent_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,input.caseId,session.userId,hashInvite(`email:${email}`),encryptSensitive(email,`advocate-invite:${id}:email`),input.helperType,hashInvite(`invite:${token}`),input.expiresAt,input.permissions,input.sensitiveCategories,consentId]);await audit(client,session.userId,"advocate.invited","advocate_invitation",id,{caseId:input.caseId,permissions:input.permissions,sensitiveCategories:input.sensitiveCategories,delivery:"not_sent_mail_gate_open"});await client.query("COMMIT");return{id,inviteToken:process.env.APP_ENV==="development"||process.env.APP_ENV==="test"?token:undefined,delivery:"copy_manually"}}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
export async function acceptInvitation(session:Session,token:string){const client=await getPool().connect();try{await client.query("BEGIN");const invite=await client.query<any>(`SELECT i.* FROM advocate_invitations i JOIN users u ON u.id=$2 WHERE i.token_hash=$1 AND i.invitee_email_hash=u.email_hash AND i.expires_at>now() AND i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.suspended_at IS NULL FOR UPDATE`,[hashInvite(`invite:${token}`),session.userId]);if(!invite.rowCount){await client.query("ROLLBACK");return null}const row=invite.rows[0],grantId=randomUUID();await client.query("UPDATE advocate_invitations SET accepted_by=$1,accepted_at=now() WHERE id=$2",[session.userId,row.id]);await client.query("INSERT INTO case_access_grants (id,case_id,grantee_user_id,invitation_id,consent_id,starts_at,expires_at) VALUES ($1,$2,$3,$4,$5,now(),$6)",[grantId,row.case_id,session.userId,row.id,row.consent_id,row.expires_at]);for(const permission of row.requested_permissions)await client.query("INSERT INTO case_access_permissions (grant_id,permission) VALUES ($1,$2)",[grantId,permission]);const sensitiveCategories=Array.isArray(row.requested_sensitive_categories)?row.requested_sensitive_categories:String(row.requested_sensitive_categories).replace(/^\{|\}$/g,"").split(",").filter(Boolean);for(const sensitivity of sensitiveCategories)await client.query("INSERT INTO case_access_permissions (grant_id,permission,sensitivity) VALUES ($1,'view_profile_fields',$2) ON CONFLICT DO NOTHING",[grantId,sensitivity]);await audit(client,session.userId,"advocate.invitation_accepted","case_access_grant",grantId,{caseId:row.case_id});await client.query("COMMIT");return{caseId:row.case_id,grantId}}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
export async function createConsent(session:Session,input:any){const access=await checkCaseAccess(session,input.caseId);if(access?.role!=="owner")return null;const id=randomUUID();await getPool().query(`INSERT INTO case_consents (id,case_id,owner_user_id,recipient,purpose,field_keys,document_ids,permitted_actions,starts_at,expires_at,contact_channel,onward_sharing,include_new_information) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[id,input.caseId,session.userId,input.recipient,input.purpose,input.fieldKeys,input.documentIds,input.permittedActions,input.startsAt,input.expiresAt,input.contactChannel??null,input.onwardSharing,input.includeNewInformation]);return{id}}
export async function revokeConsent(session:Session,id:string){const client=await getPool().connect();try{await client.query("BEGIN");const result=await client.query("UPDATE case_consents SET revoked_at=now(),revocation_method='user_control' WHERE id=$1 AND owner_user_id=$2 AND revoked_at IS NULL RETURNING case_id",[id,session.userId]);if(!result.rowCount){await client.query("ROLLBACK");return false}await client.query("UPDATE case_access_grants SET revoked_at=now() WHERE consent_id=$1 AND revoked_at IS NULL",[id]);await client.query("UPDATE advocate_invitations SET revoked_at=now() WHERE consent_id=$1 AND revoked_at IS NULL",[id]);await audit(client,session.userId,"consent.revoked","case_consent",id,{caseId:result.rows[0].case_id});await client.query("COMMIT");return true}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
export async function createDocument(session:Session,caseId:string,input:any){if(!await checkCaseAccess(session,caseId,"prepare_letters"))return null;const id=randomUUID(),versionId=randomUUID(),client=await getPool().connect();try{await client.query("BEGIN");if(input.consentId){const consent=await client.query("SELECT 1 FROM case_consents WHERE id=$1 AND case_id=$2 AND starts_at<=now() AND expires_at>now() AND revoked_at IS NULL",[input.consentId,caseId]);if(!consent.rowCount){await client.query("ROLLBACK");return null}}await client.query("INSERT INTO case_documents (id,case_id,document_type,template_id,template_version,title,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7)",[id,caseId,input.documentType,input.templateId,input.templateVersion,input.title,session.userId]);await client.query("INSERT INTO case_document_versions (id,document_id,version,body_encrypted,profile_fields,case_fields,evidence_ids,consent_id,created_by) VALUES ($1,$2,1,$3,$4,$5,$6,$7,$8)",[versionId,id,encryptSensitive(input.body,`case-document-version:${versionId}`),input.profileFields,input.caseFields,input.evidenceIds,input.consentId??null,session.userId]);await audit(client,session.userId,"document.draft_created","case_document",id,{caseId,templateId:input.templateId,templateVersion:input.templateVersion,version:1});await client.query("COMMIT");return{id,version:1,status:"draft"}}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
export async function createSuitability(session:Session,caseId:string,input:any){const access=await checkCaseAccess(session,caseId);if(access?.role!=="owner")return null;const id=randomUUID();await getPool().query("INSERT INTO suitability_assessments (id,case_id,accommodation_address_encrypted,offered_at,assessment,urgent_risks,user_view_encrypted,status,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)",[id,caseId,enc(input.accommodationAddress,`suitability:${id}:address`),input.offeredAt??null,input.assessment,input.urgentRisks,enc(input.userView,`suitability:${id}:user-view`),input.status,session.userId]);return{id,status:input.status}}
export async function createComplaint(session:Session,caseId:string,input:any){const access=await checkCaseAccess(session,caseId);if(access?.role!=="owner")return null;const id=randomUUID();await getPool().query("INSERT INTO case_complaints (id,case_id,route,destination,deadline_at,summary_encrypted,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7)",[id,caseId,input.route,input.destination??null,input.deadlineAt??null,encryptSensitive(input.summary,`complaint:${id}:summary`),session.userId]);return{id,status:"draft"}}
export async function createReview(session:Session,caseId:string,input:any){const access=await checkCaseAccess(session,caseId);if(access?.role!=="owner")return null;const id=randomUUID();await getPool().query("INSERT INTO case_reviews (id,case_id,decision_type,decision_received_at,in_writing,reasons_encrypted,deadline_at,deadline_status,delay_reason_encrypted,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[id,caseId,input.decisionType,input.decisionReceivedAt??null,input.inWriting??null,enc(input.reasons,`review:${id}:reasons`),input.deadlineAt??null,input.deadlineStatus,enc(input.delayReason,`review:${id}:delay`),session.userId]);return{id,status:"draft"}}
export async function searchCase(session:Session,caseId:string,query:string){const access=await checkCaseAccess(session,caseId);if(access?.role!=="owner")return null;const pattern=`%${query.replaceAll("%","\\%").replaceAll("_","\\_")}%`;const result=await getPool().query<{resource_type:string;resource_id:string;label:string}>(`SELECT 'event' resource_type,id resource_id,coalesce(organisation,event_type) label FROM case_events WHERE case_id=$1 AND (organisation ILIKE $2 ESCAPE '\\' OR event_type ILIKE $2 ESCAPE '\\') UNION ALL SELECT 'application',id,destination FROM case_applications WHERE case_id=$1 AND (destination ILIKE $2 ESCAPE '\\' OR kind ILIKE $2 ESCAPE '\\' OR status ILIKE $2 ESCAPE '\\') UNION ALL SELECT 'deadline',id,title FROM case_deadlines WHERE case_id=$1 AND title ILIKE $2 ESCAPE '\\' UNION ALL SELECT 'duty',id,duty_type FROM case_duties WHERE case_id=$1 AND duty_type ILIKE $2 ESCAPE '\\' UNION ALL SELECT 'task',id,title FROM case_tasks WHERE case_id=$1 AND title ILIKE $2 ESCAPE '\\' LIMIT 50`,[caseId,pattern]);await getPool().query("INSERT INTO audit_events (id,actor_id,event_type,resource_type,resource_id,metadata) VALUES ($1,$2,'case.searched','case',$3,$4)",[randomUUID(),session.userId,caseId,{queryHash:hashInvite(`search:${query.toLowerCase()}`),resultCount:result.rowCount}]);return result.rows}
