import "server-only";

import { createHash, randomBytes, randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import { annualisedCost, pilotActivationBlockers, suppressSmallCells, type GateState, type PilotActivationInput } from "@/domain/pilot-operations";
import { getPool } from "@/server/db/pool";
import { getEnvironment } from "@/server/env";
import { decryptSensitive, encryptSensitive } from "@/server/security/encryption";
import type { OperationalActor, OperationalRole } from "@/server/operations-auth";

type Json = Record<string, unknown> | unknown[];
const sha256 = (value: string) => createHash("sha256").update(value).digest("hex");
const json = (value: unknown) => JSON.stringify(value);

async function audit(client: PoolClient, actorId: string | null, eventType: string, resourceType: string, resourceId: string | null, metadata: Record<string, unknown> = {}) {
  await client.query("INSERT INTO audit_events (id,actor_id,event_type,resource_type,resource_id,metadata) VALUES ($1,$2,$3,$4,$5,$6)", [randomUUID(), actorId, eventType, resourceType, resourceId, metadata]);
}

async function transaction<T>(work: (client: PoolClient) => Promise<T>): Promise<T> {
  const client = await getPool().connect();
  try { await client.query("BEGIN"); const value = await work(client); await client.query("COMMIT"); return value; }
  catch (error) { await client.query("ROLLBACK").catch(() => {}); throw error; }
  finally { client.release(); }
}

export async function listPilots() {
  return (await getPool().query("SELECT id,name,description,region,status,start_date,end_date,maximum_users,maximum_professionals,support_hours,created_at,approved_at FROM pilot_programs ORDER BY created_at DESC")).rows;
}
export async function listPilotsFor(actor:OperationalActor){if(actor.administrator)return listPilots();return(await getPool().query("SELECT DISTINCT p.id,p.name,p.description,p.region,p.status,p.start_date,p.end_date,p.maximum_users,p.maximum_professionals,p.support_hours,p.created_at,p.approved_at FROM pilot_programs p JOIN operational_role_assignments r ON r.pilot_id=p.id WHERE r.user_id=$1 AND r.status='active' AND (r.expires_at IS NULL OR r.expires_at>now()) ORDER BY p.created_at DESC",[actor.userId])).rows;}

export async function getPilot(pilotId: string) {
  const [pilot, cohorts, flags, approvals] = await Promise.all([
    getPool().query("SELECT * FROM pilot_programs WHERE id=$1", [pilotId]),
    getPool().query("SELECT * FROM pilot_cohorts WHERE pilot_id=$1 ORDER BY created_at", [pilotId]),
    getPool().query("SELECT * FROM pilot_feature_flags WHERE pilot_id IS NULL OR pilot_id=$1 ORDER BY id", [pilotId]),
    getPool().query("SELECT * FROM pilot_approvals WHERE pilot_id=$1 ORDER BY approval_type", [pilotId]),
  ]);
  return pilot.rowCount ? { ...pilot.rows[0], cohorts: cohorts.rows, flags: flags.rows, approvals: approvals.rows } : null;
}

export async function createPilot(actorId: string, input: Record<string, unknown>) {
  return transaction(async (client) => {
    const id = randomUUID();
    await client.query(`INSERT INTO pilot_programs (id,name,description,region,start_date,end_date,maximum_users,maximum_professionals,support_hours,safeguarding_owner_id,technical_owner_id,editorial_owner_id,data_verification_owner_id,support_owner_id,incident_owner_id,entry_criteria,exit_criteria,pause_criteria,stop_criteria,created_by)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)`, [id,input.name,input.description,input.region,input.startDate ?? null,input.endDate ?? null,input.maximumUsers,input.maximumProfessionals,input.supportHours,input.safeguardingOwnerId ?? null,input.technicalOwnerId ?? null,input.editorialOwnerId ?? null,input.dataVerificationOwnerId ?? null,input.supportOwnerId ?? null,input.incidentOwnerId ?? null,json(input.entryCriteria),json(input.exitCriteria),json(input.pauseCriteria),json(input.stopCriteria),actorId]);
    for (const approvalType of ["pilot","safeguarding","governance","accessibility","security","data","support","incident","recovery"]) await client.query("INSERT INTO pilot_approvals (id,pilot_id,approval_type) VALUES ($1,$2,$3)", [randomUUID(),id,approvalType]);
    await audit(client,actorId,"pilot.created","pilot",id,{ region: input.region, maximumUsers: input.maximumUsers });
    return { id, status: "draft" };
  });
}

export async function updatePilot(actorId: string, pilotId: string, input: Record<string, unknown>) {
  const mapping: Record<string,string> = { name:"name",description:"description",region:"region",startDate:"start_date",endDate:"end_date",maximumUsers:"maximum_users",maximumProfessionals:"maximum_professionals",supportHours:"support_hours",safeguardingOwnerId:"safeguarding_owner_id",technicalOwnerId:"technical_owner_id",editorialOwnerId:"editorial_owner_id",dataVerificationOwnerId:"data_verification_owner_id",supportOwnerId:"support_owner_id",incidentOwnerId:"incident_owner_id",entryCriteria:"entry_criteria",exitCriteria:"exit_criteria",pauseCriteria:"pause_criteria",stopCriteria:"stop_criteria" };
  return transaction(async (client) => {
    const entries = Object.entries(input).filter(([key]) => key !== "status" && mapping[key]);
    if (entries.length) await client.query(`UPDATE pilot_programs SET ${entries.map(([key],index)=>`${mapping[key]}=$${index+1}`).join(",")} WHERE id=$${entries.length+1}`, [...entries.map(([key,value])=>["entryCriteria","exitCriteria","pauseCriteria","stopCriteria"].includes(key)?json(value):value),pilotId]);
    if (input.status) {
      const allowed: Record<string,string[]> = { draft:["awaiting_approval"],awaiting_approval:["draft","approved"],approved:["scheduled","paused","stopped"],scheduled:["paused","stopped"],active:["paused","stopped","completed"],paused:["active","stopped","completed"],stopped:["archived"],completed:["archived"],archived:[] };
      const current = await client.query<{status:string}>("SELECT status FROM pilot_programs WHERE id=$1 FOR UPDATE",[pilotId]);
      if (!current.rowCount || !allowed[current.rows[0]!.status]?.includes(String(input.status))) throw new Error("Pilot status transition is not permitted.");
      if (input.status === "approved") throw new Error("Pilot approval requires the dedicated human approval workflow.");
      if (input.status === "active") throw new Error("Pilot activation requires the fail-closed activation workflow.");
      await client.query("UPDATE pilot_programs SET status=$1 WHERE id=$2",[input.status,pilotId]);
    }
    await audit(client,actorId,"pilot.updated","pilot",pilotId,{ fields:Object.keys(input) });
    return { id:pilotId };
  });
}

export async function approvePilot(actorId: string, pilotId: string, approvalType: string, evidence: Json) {
  return transaction(async (client) => {
    await client.query("UPDATE pilot_approvals SET status='approved',evidence=$1,decided_by=$2,decided_at=now() WHERE pilot_id=$3 AND approval_type=$4",[json(evidence),actorId,pilotId,approvalType]);
    const pending = await client.query("SELECT 1 FROM pilot_approvals WHERE pilot_id=$1 AND status<>'approved'",[pilotId]);
    if (!pending.rowCount) await client.query("UPDATE pilot_programs SET status='approved',approved_by=$1,approved_at=now() WHERE id=$2 AND status='awaiting_approval'",[actorId,pilotId]);
    await audit(client,actorId,"pilot.approval_recorded","pilot",pilotId,{ approvalType });
    return { pilotId, approvalType, approved:true };
  });
}

export async function createCohort(actorId:string,pilotId:string,input:Record<string,unknown>) {
  return transaction(async(client)=>{const id=randomUUID();await client.query(`INSERT INTO pilot_cohorts (id,pilot_id,name,description,participant_type,maximum_participants,start_date,end_date,features_available,support_model,consent_version,data_permitted,exit_criteria) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[id,pilotId,input.name,input.description,input.participantType,input.maximumParticipants,input.startDate??null,input.endDate??null,input.featuresAvailable,input.supportModel,input.consentVersion,input.dataPermitted,json(input.exitCriteria)]);await audit(client,actorId,"pilot.cohort_created","pilot_cohort",id,{pilotId,participantType:input.participantType});return{id,status:"draft"};});
}

export async function approveCohort(actorId:string,pilotId:string,cohortId:string){return transaction(async(client)=>{const result=await client.query("UPDATE pilot_cohorts SET status='approved',approved_by=$1,approved_at=now() WHERE id=$2 AND pilot_id=$3 AND status IN ('draft','awaiting_approval') RETURNING id",[actorId,cohortId,pilotId]);if(!result.rowCount)throw new Error("Cohort cannot be approved from its current state.");await audit(client,actorId,"pilot.cohort_approved","pilot_cohort",cohortId,{pilotId});return{id:cohortId,status:"approved"};});}

export async function inviteParticipant(actorId:string,pilotId:string,input:Record<string,unknown>){return transaction(async(client)=>{const cohort=await client.query<{maximum_participants:number}>("SELECT maximum_participants FROM pilot_cohorts WHERE id=$1 AND pilot_id=$2 AND status='approved' FOR UPDATE",[input.cohortId,pilotId]);if(!cohort.rowCount)throw new Error("Participant invitations require an approved cohort.");const count=await client.query<{count:number}>("SELECT count(*)::int count FROM pilot_participants WHERE cohort_id=$1 AND status NOT IN ('withdrawn','deleted')",[input.cohortId]);if(count.rows[0]!.count>=cohort.rows[0]!.maximum_participants)throw new Error("Cohort participant limit has been reached.");const id=randomUUID(),token=randomBytes(32).toString("base64url");const sensitive=(name:string,value:unknown)=>value?encryptSensitive(String(value),`pilot-participant:${id}:${name}`):null;await client.query(`INSERT INTO pilot_participants (id,pilot_id,cohort_id,invitation_hash,eligibility_status,safe_contact_encrypted,support_needs_encrypted,accessibility_preferences_encrypted) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,[id,pilotId,input.cohortId,sha256(token),input.eligibilityStatus,sensitive("safe-contact",input.safeContact??input.email),sensitive("support-needs",input.supportNeeds),sensitive("accessibility",input.accessibilityPreferences)]);await audit(client,actorId,"pilot.participant_invited","pilot_participant",id,{pilotId,cohortId:input.cohortId});return{id,invitationToken:token,status:"invited"};});}

export async function acceptParticipantInvitation(userId:string,token:string){return transaction(async(client)=>{const result=await client.query<{id:string;pilot_id:string;cohort_id:string}>("UPDATE pilot_participants SET user_id=$1,status='information_viewed' WHERE invitation_hash=$2 AND user_id IS NULL AND eligibility_status='eligible' AND status='invited' RETURNING id,pilot_id,cohort_id",[userId,sha256(token)]);if(!result.rowCount)throw new Error("Invitation is invalid, already used or not eligible.");await audit(client,userId,"pilot.invitation_accepted","pilot_participant",result.rows[0]!.id,{pilotId:result.rows[0]!.pilot_id,cohortId:result.rows[0]!.cohort_id});return{id:result.rows[0]!.id,status:"information_viewed",consentsRequired:["service_use","pilot_participation"]};});}

export async function withdrawParticipant(actorId:string,participantId:string){return transaction(async(client)=>{await client.query("UPDATE pilot_participants SET status='withdrawn',eligibility_status='withdrawn',withdrawn_at=now() WHERE id=$1",[participantId]);await client.query("UPDATE pilot_participant_consents SET revoked_at=COALESCE(revoked_at,now()) WHERE participant_id=$1 AND consent_type<>'service_use'",[participantId]);await audit(client,actorId,"pilot.participant_withdrew","pilot_participant",participantId);return{id:participantId,status:"withdrawn"};});}

export async function requestParticipantData(actorId:string,participantId:string,requestType:"export"|"deletion"){return transaction(async(client)=>{const column=requestType==="export"?"export_requested_at":"deletion_requested_at";const result=await client.query(`UPDATE pilot_participants SET ${column}=now() WHERE id=$1 RETURNING id`,[participantId]);if(!result.rowCount)throw new Error("Participant was not found.");await audit(client,actorId,`pilot.participant_${requestType}_requested`,"pilot_participant",participantId);return{id:participantId,requestType,status:"recorded"};});}

export async function setParticipantConsent(actorId:string,participantId:string,input:{consentType:string;noticeVersion:string;granted:boolean}){return transaction(async(client)=>{await client.query(`INSERT INTO pilot_participant_consents (id,participant_id,consent_type,notice_version,granted_at,revoked_at) VALUES ($1,$2,$3,$4,CASE WHEN $5 THEN now() END,CASE WHEN $5 THEN NULL ELSE now() END) ON CONFLICT(participant_id,consent_type,notice_version) DO UPDATE SET granted_at=CASE WHEN $5 THEN now() ELSE pilot_participant_consents.granted_at END,revoked_at=CASE WHEN $5 THEN NULL ELSE now() END`,[randomUUID(),participantId,input.consentType,input.noticeVersion,input.granted]);const required=await client.query("SELECT consent_type FROM pilot_participant_consents WHERE participant_id=$1 AND consent_type IN ('service_use','pilot_participation') AND granted_at IS NOT NULL AND revoked_at IS NULL GROUP BY consent_type",[participantId]);if(required.rowCount===2)await client.query("UPDATE pilot_participants SET status='active',joined_at=COALESCE(joined_at,now()) WHERE id=$1 AND eligibility_status='eligible' AND status IN ('information_viewed','consented')",[participantId]);else await client.query("UPDATE pilot_participants SET status=CASE WHEN status='active' THEN 'paused' ELSE status END WHERE id=$1",[participantId]);await audit(client,actorId,input.granted?"pilot.consent_granted":"pilot.consent_revoked","pilot_participant",participantId,{consentType:input.consentType,noticeVersion:input.noticeVersion});return{id:participantId,consentType:input.consentType,granted:input.granted};});}

const requiredActivationGates = ["PHASE4-INTEGRATION-001","DATA-001","DEPLOY-001","AUTH-001","ACCESS-001","GOV-001","CASE-001","SAFEGUARD-001","RETENTION-001","PHASE5-PILOT-001","PHASE5-SUPPORT-001","PHASE5-INCIDENT-001"];
export async function pilotPreflight(pilotId:string){const [pilot,gates,cohort,flags,approvals]=await Promise.all([getPool().query("SELECT * FROM pilot_programs WHERE id=$1",[pilotId]),getPool().query<GateState>("SELECT id,status,human_approval_required \"humanApprovalRequired\",approved_at \"approvedAt\" FROM operational_release_gates WHERE id=ANY($1)",[requiredActivationGates]),getPool().query("SELECT 1 FROM pilot_cohorts WHERE pilot_id=$1 AND status='approved'",[pilotId]),getPool().query<{id:string;defaultState:boolean}>("SELECT id,default_state \"defaultState\" FROM pilot_feature_flags"),getPool().query<{approval_type:string;status:string}>("SELECT approval_type,status FROM pilot_approvals WHERE pilot_id=$1",[pilotId])]);if(!pilot.rowCount)return null;const row=pilot.rows[0];const approved=new Set(approvals.rows.filter(a=>a.status==="approved").map(a=>a.approval_type));const input:PilotActivationInput={status:row.status,maximumUsers:row.maximum_users,owners:{safeguarding:row.safeguarding_owner_id,technical:row.technical_owner_id,editorial:row.editorial_owner_id,dataVerification:row.data_verification_owner_id,support:row.support_owner_id,incident:row.incident_owner_id},cohortApproved:Boolean(cohort.rowCount),supportConfigured:Boolean(row.support_hours&&approved.has("support")),backupVerified:approved.has("recovery"),rollbackVerified:approved.has("recovery")};const blockers=pilotActivationBlockers(input,gates.rows,flags.rows);return{pilotId,ready:blockers.length===0,blockers,checkedAt:new Date().toISOString(),activatesNothing:true};}

export async function activatePilot(actorId:string,pilotId:string){const environment=getEnvironment();if(environment.APP_ENV!=="pilot"||environment.PILOT_ACTIVATION_ENABLED!=="true")throw new Error("Pilot activation is disabled by environment configuration.");const preflight=await pilotPreflight(pilotId);if(!preflight||!preflight.ready)throw new Error(`Pilot activation is blocked: ${preflight?.blockers.join(" ")??"pilot not found"}`);return transaction(async(client)=>{const result=await client.query("UPDATE pilot_programs SET status='active' WHERE id=$1 AND status IN ('approved','scheduled') RETURNING id",[pilotId]);if(!result.rowCount)throw new Error("Pilot is not in an activatable state.");await audit(client,actorId,"pilot.activated","pilot",pilotId,{environment:environment.APP_ENV});return{id:pilotId,status:"active"};});}

export async function listFeatureFlags(){return(await getPool().query("SELECT * FROM pilot_feature_flags ORDER BY environment,id")).rows;}
export async function changeFeatureFlag(actorId:string,flagId:string,input:{enabled:boolean;reason:string;approvals:string[]}){return transaction(async(client)=>{const flag=await client.query<{current_state:boolean;dependencies:string[]}>("SELECT current_state,dependencies FROM pilot_feature_flags WHERE id=$1 FOR UPDATE",[flagId]);if(!flag.rowCount)throw new Error("Feature flag was not found.");if(input.enabled){const open=await client.query<{id:string}>("SELECT id FROM operational_release_gates WHERE id=ANY($1) AND status<>'closed'",[flag.rows[0]!.dependencies]);if(open.rowCount)throw new Error(`Feature cannot be enabled while gates are open: ${open.rows.map(r=>r.id).join(", ")}.`);if(flagId==="production.public_access")throw new Error("Production public access cannot be enabled through the feature API.");}await client.query("UPDATE pilot_feature_flags SET current_state=$1,last_changed_at=now(),changed_by=$2,change_reason=$3 WHERE id=$4",[input.enabled,actorId,input.reason,flagId]);await client.query("INSERT INTO pilot_feature_flag_history (id,flag_id,previous_state,new_state,changed_by,reason,approvals) VALUES ($1,$2,$3,$4,$5,$6,$7)",[randomUUID(),flagId,flag.rows[0]!.current_state,input.enabled,actorId,input.reason,json(input.approvals)]);await audit(client,actorId,"feature_flag.changed","feature_flag",flagId,{previousState:flag.rows[0]!.current_state,newState:input.enabled});return{id:flagId,enabled:input.enabled};});}

const responseHours={critical:1,high:4,material:24,standard:72};
export async function createSupportTicket(actorId:string|null,input:Record<string,unknown>){return transaction(async(client)=>{const id=randomUUID(),severity=String(input.severity) as keyof typeof responseHours;await client.query(`INSERT INTO support_tickets (id,reporter_user_id,anonymous_reporter,category,severity,description_encrypted,safe_contact_encrypted,related_case_id,related_service_external_id,related_council_external_id,pilot_id,response_deadline) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,now()+($12||' hours')::interval)`,[id,input.anonymous?null:actorId,input.anonymous,input.category,severity,encryptSensitive(String(input.description),`support-ticket:${id}:description`),input.safeContact?encryptSensitive(String(input.safeContact),`support-ticket:${id}:contact`):null,input.relatedCaseId??null,input.relatedServiceExternalId??null,input.relatedCouncilExternalId??null,input.pilotId??null,responseHours[severity]]);await audit(client,actorId,input.category==="safeguarding"?"support.safeguarding_escalated":"support.ticket_created","support_ticket",id,{category:input.category,severity});return{id,status:"open",safeguardingEscalated:input.category==="safeguarding",responseDeadlineHours:responseHours[severity]};});}
export async function listSupportTickets(){return(await getPool().query("SELECT id,anonymous_reporter,category,severity,related_case_id,related_service_external_id,related_council_external_id,pilot_id,assigned_owner_id,status,response_deadline,created_at,updated_at FROM support_tickets ORDER BY CASE severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'material' THEN 2 ELSE 3 END,response_deadline")).rows;}
export async function listSupportTicketsFor(actor:OperationalActor){if(actor.administrator)return listSupportTickets();return(await getPool().query("SELECT DISTINCT t.id,t.anonymous_reporter,t.category,t.severity,t.related_case_id,t.related_service_external_id,t.related_council_external_id,t.pilot_id,t.assigned_owner_id,t.status,t.response_deadline,t.created_at,t.updated_at FROM support_tickets t JOIN operational_role_assignments r ON r.user_id=$1 AND r.status='active' AND (r.expires_at IS NULL OR r.expires_at>now()) WHERE r.pilot_id IS NULL OR r.pilot_id=t.pilot_id ORDER BY t.response_deadline",[actor.userId])).rows;}
export async function getSupportTicket(ticketId:string){const result=await getPool().query("SELECT * FROM support_tickets WHERE id=$1",[ticketId]);if(!result.rowCount)return null;const row=result.rows[0];return{...row,description:decryptSensitive(row.description_encrypted,`support-ticket:${ticketId}:description`),safeContact:row.safe_contact_encrypted?decryptSensitive(row.safe_contact_encrypted,`support-ticket:${ticketId}:contact`):null,resolution:row.resolution_encrypted?decryptSensitive(row.resolution_encrypted,`support-ticket:${ticketId}:resolution`):null,description_encrypted:undefined,safe_contact_encrypted:undefined,resolution_encrypted:undefined};}
export async function updateSupportTicket(actorId:string,ticketId:string,input:{assignedOwnerId?:string|null;status?:string;resolution?:string}){return transaction(async client=>{const fields:string[]=[],values:unknown[]=[];if(Object.hasOwn(input,"assignedOwnerId")){values.push(input.assignedOwnerId??null);fields.push(`assigned_owner_id=$${values.length}`);}if(input.status){values.push(input.status);fields.push(`status=$${values.length}`);}if(input.resolution){values.push(encryptSensitive(input.resolution,`support-ticket:${ticketId}:resolution`));fields.push(`resolution_encrypted=$${values.length}`);}if(input.status==="closed"){fields.push("closed_at=now()");}fields.push("updated_at=now()");values.push(ticketId);const result=await client.query(`UPDATE support_tickets SET ${fields.join(",")} WHERE id=$${values.length} RETURNING id,status`,values);if(!result.rowCount)throw new Error("Support ticket was not found.");await audit(client,actorId,"support.ticket_updated","support_ticket",ticketId,{status:input.status??null,assignedOwnerChanged:Object.hasOwn(input,"assignedOwnerId"),resolutionRecorded:Boolean(input.resolution)});return result.rows[0];});}

export async function createIncident(actorId:string,input:Record<string,unknown>){return transaction(async(client)=>{const id=randomUUID();await client.query(`INSERT INTO operational_incidents (id,severity,category,summary,detected_by,affected_system,affected_records,safeguarding_impact,privacy_impact,security_impact,incident_commander_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,input.severity,input.category,input.summary,actorId,input.affectedSystem,input.affectedRecords,input.safeguardingImpact,input.privacyImpact,input.securityImpact,input.incidentCommanderId??null]);await audit(client,actorId,"incident.created","incident",id,{severity:input.severity,category:input.category,affectedSystem:input.affectedSystem});return{id,status:"open"};});}
export async function listIncidents(){return(await getPool().query("SELECT * FROM operational_incidents ORDER BY CASE severity WHEN 'p0' THEN 0 WHEN 'p1' THEN 1 WHEN 'p2' THEN 2 ELSE 3 END,detected_at DESC")).rows;}
export async function getIncident(incidentId:string){const [incident,actions]=await Promise.all([getPool().query("SELECT * FROM operational_incidents WHERE id=$1",[incidentId]),getPool().query("SELECT * FROM incident_actions WHERE incident_id=$1 ORDER BY performed_at",[incidentId])]);return incident.rowCount?{...incident.rows[0],actions:actions.rows}:null;}
export async function updateIncident(actorId:string,incidentId:string,input:Record<string,unknown>){const mapping:Record<string,string>={incidentCommanderId:"incident_commander_id",status:"status",containmentAction:"containment_action",communicationStatus:"communication_status",regulatorAssessment:"regulator_assessment",rootCause:"root_cause",remediation:"remediation",postIncidentReview:"post_incident_review"};return transaction(async client=>{const entries=Object.entries(input);const values=entries.map(([key,value])=>key==="postIncidentReview"?json(value):value);values.push(incidentId);const result=await client.query(`UPDATE operational_incidents SET ${entries.map(([key],index)=>`${mapping[key]}=$${index+1}`).join(",")},updated_at=now()${input.status==="closed"?",closed_at=now()":""} WHERE id=$${values.length} RETURNING id,status`,values);if(!result.rowCount)throw new Error("Incident was not found.");await audit(client,actorId,"incident.updated","incident",incidentId,{fields:Object.keys(input),status:input.status??null});return result.rows[0];});}

export async function performIncidentAction(actorId:string,incidentId:string,input:{actionType:string;targetType:string;targetId?:string;reason:string}){return transaction(async(client)=>{const incident=await client.query("SELECT 1 FROM operational_incidents WHERE id=$1 FOR UPDATE",[incidentId]);if(!incident.rowCount)throw new Error("Incident was not found.");let previous:Json={},next:Json={};if(["disable_feature","disable_evidence","disable_email","disable_advocate_invites","pause_registration"].includes(input.actionType)){const flagId=input.actionType==="disable_evidence"?"pilot.evidence":input.actionType==="disable_email"?"pilot.external_email":input.actionType==="disable_advocate_invites"?"pilot.advocates":input.actionType==="pause_registration"?"pilot.registration":input.targetId;const row=await client.query<{current_state:boolean}>("SELECT current_state FROM pilot_feature_flags WHERE id=$1 FOR UPDATE",[flagId]);if(!row.rowCount)throw new Error("Target feature flag was not found.");previous={enabled:row.rows[0]!.current_state};next={enabled:false};await client.query("UPDATE pilot_feature_flags SET current_state=false,last_changed_at=now(),changed_by=$1,change_reason=$2 WHERE id=$3",[actorId,input.reason,flagId]);await client.query("INSERT INTO pilot_feature_flag_history (id,flag_id,previous_state,new_state,changed_by,reason) VALUES ($1,$2,$3,false,$4,$5)",[randomUUID(),flagId,row.rows[0]!.current_state,actorId,input.reason]);}else if(input.actionType==="pause_pilot"){const row=await client.query<{status:string}>("SELECT status FROM pilot_programs WHERE id=$1 FOR UPDATE",[input.targetId]);if(!row.rowCount)throw new Error("Target pilot was not found.");previous={status:row.rows[0]!.status};next={status:"paused"};await client.query("UPDATE pilot_programs SET status='paused' WHERE id=$1 AND status IN ('active','approved','scheduled')",[input.targetId]);}else if(input.actionType==="hide_service"){previous={hidden:false};next={hidden:true};await client.query("UPDATE service_correction_proposals SET temporarily_hidden_at=now(),hidden_by=$1 WHERE record_type='service' AND record_external_id=$2 AND urgency='critical'",[actorId,input.targetId]);}else{next={recorded:true};}await client.query("INSERT INTO incident_actions (id,incident_id,action_type,target_type,target_id,previous_state,new_state,reason,performed_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)",[randomUUID(),incidentId,input.actionType,input.targetType,input.targetId??null,previous,next,input.reason,actorId]);await client.query("UPDATE operational_incidents SET containment_action=$1,status=CASE WHEN status='open' THEN 'contained' ELSE status END,updated_at=now() WHERE id=$2",[input.reason,incidentId]);await audit(client,actorId,"incident.emergency_action","incident",incidentId,{actionType:input.actionType,targetType:input.targetType,targetId:input.targetId??null});return{incidentId,action:input.actionType,previousState:previous,newState:next};});}

export async function createFeedback(actorId:string|null,input:Record<string,unknown>){return transaction(async(client)=>{const id=randomUUID(),tracking=randomBytes(24).toString("base64url");await client.query(`INSERT INTO pilot_feedback (id,reporter_user_id,anonymous,category,rating,text_encrypted,related_page,related_service_external_id,related_council_external_id,cohort_id,tracking_token_hash) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,input.anonymous?null:actorId,input.anonymous,input.category,input.rating??null,input.text?encryptSensitive(String(input.text),`pilot-feedback:${id}:text`):null,input.relatedPage??null,input.relatedServiceExternalId??null,input.relatedCouncilExternalId??null,input.cohortId??null,input.anonymous?null:sha256(tracking)]);await audit(client,actorId,["safeguarding","privacy"].includes(String(input.category))?"feedback.escalated":"feedback.created","pilot_feedback",id,{category:input.category,anonymous:input.anonymous});return{id,status:"open",trackingToken:input.anonymous?undefined:tracking};});}
export async function listFeedback(){return(await getPool().query("SELECT id,anonymous,category,rating,related_page,related_service_external_id,related_council_external_id,cohort_id,status,created_at FROM pilot_feedback ORDER BY created_at DESC")).rows;}

export async function recordOutcome(actorId:string,input:Record<string,unknown>){const id=randomUUID();await getPool().query("INSERT INTO pilot_outcomes (id,pilot_id,cohort_id,participant_id,outcome_type,occurred_on,region,source,confidence) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$8)",[id,input.pilotId,input.cohortId??null,input.participantId??null,input.outcomeType,input.occurredOn,input.region,input.source]);await getPool().query("INSERT INTO audit_events (id,actor_id,event_type,resource_type,resource_id,metadata) VALUES ($1,$2,'outcome.recorded','pilot_outcome',$3,$4)",[randomUUID(),actorId,id,{outcomeType:input.outcomeType,pilotId:input.pilotId}]);return{id,optional:true};}
export async function aggregateOutcomes(pilotId:string,minimum=5){const rows=await getPool().query<{outcome_type:string;region:string;count:number}>("SELECT outcome_type,region,count(*)::int count FROM pilot_outcomes WHERE pilot_id=$1 GROUP BY outcome_type,region ORDER BY outcome_type,region",[pilotId]);return suppressSmallCells(rows.rows,minimum);}

export async function createPartner(actorId:string,input:Record<string,unknown>){return transaction(async(client)=>{const id=randomUUID(),enc=(key:string,value:unknown)=>value?encryptSensitive(String(value),`partner:${id}:${key}`):null;await client.query("INSERT INTO partner_organisations (id,name,partner_type,region,primary_contact_encrypted,safeguarding_contact_encrypted,data_protection_contact_encrypted) VALUES ($1,$2,$3,$4,$5,$6,$7)",[id,input.name,input.partnerType,input.region,enc("primary",input.primaryContact),enc("safeguarding",input.safeguardingContact),enc("data-protection",input.dataProtectionContact)]);await audit(client,actorId,"partner.created","partner_organisation",id,{region:input.region,partnerType:input.partnerType});return{id,status:"pending"};});}
export async function listPartners(){return(await getPool().query("SELECT id,name,partner_type,region,status,agreement_status,training_status,verification_status,suspended_at,revoked_at,created_at FROM partner_organisations ORDER BY name")).rows;}
export async function listPartnersFor(actor:OperationalActor){if(actor.administrator||actor.roles.includes("data_reviewer"))return listPartners();return(await getPool().query("SELECT o.id,o.name,o.partner_type,o.region,o.status,o.agreement_status,o.training_status,o.verification_status,o.suspended_at,o.revoked_at,o.created_at FROM partner_organisations o JOIN partner_memberships m ON m.organisation_id=o.id WHERE m.user_id=$1 AND m.status='active' ORDER BY o.name",[actor.userId])).rows;}
export async function listCorrectionProposalsFor(actor:OperationalActor){if(actor.administrator||actor.roles.includes("data_reviewer"))return(await getPool().query("SELECT * FROM service_correction_proposals ORDER BY CASE urgency WHEN 'critical' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,created_at DESC")).rows;return(await getPool().query("SELECT p.* FROM service_correction_proposals p JOIN partner_memberships m ON m.organisation_id=p.partner_organisation_id WHERE m.user_id=$1 AND m.status='active' ORDER BY p.created_at DESC",[actor.userId])).rows;}
export async function proposeCorrection(actorId:string,input:Record<string,unknown>){return transaction(async(client)=>{const id=randomUUID();await client.query(`INSERT INTO service_correction_proposals (id,record_type,record_external_id,current_value,proposed_value,reason,evidence,urgency,submitted_by,partner_organisation_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,input.recordType,input.recordExternalId,json(input.currentValue),json(input.proposedValue),input.reason,json(input.evidence),input.urgency,actorId,input.partnerOrganisationId??null]);await audit(client,actorId,"correction.proposed","service_correction",id,{recordType:input.recordType,recordExternalId:input.recordExternalId,urgency:input.urgency});return{id,status:"pending",published:false};});}
export async function reviewCorrection(actorId:string,proposalId:string,decision:"verified"|"rejected",reason:string){return transaction(async(client)=>{const result=await client.query("UPDATE service_correction_proposals SET verification_status=$1,reviewer_id=$2,decision=$3 WHERE id=$4 AND verification_status IN ('pending','investigating') RETURNING id",[decision,actorId,reason,proposalId]);if(!result.rowCount)throw new Error("Proposal is not reviewable.");await audit(client,actorId,"correction.reviewed","service_correction",proposalId,{decision});return{id:proposalId,status:decision,published:false};});}
export async function linkPublishedCorrection(actorId:string,proposalId:string,datasetRevisionId:string){return transaction(async(client)=>{const proposal=await client.query<{record_type:string;record_external_id:string;created_at:Date}>("SELECT record_type,record_external_id,created_at FROM service_correction_proposals WHERE id=$1 AND verification_status='verified' AND reviewer_id IS NOT NULL FOR UPDATE",[proposalId]);if(!proposal.rowCount)throw new Error("Only an independently verified proposal can be linked to a published revision.");const revision=await client.query("SELECT id,external_version FROM dataset_revisions WHERE id=$1 AND is_active=true AND published_at IS NOT NULL AND published_at>$2",[datasetRevisionId,proposal.rows[0]!.created_at]);if(!revision.rowCount)throw new Error("Correction publication requires a newer active, published controlled dataset revision.");const table=proposal.rows[0]!.record_type==="service"?"services":"councils";const incorporated=await client.query(`SELECT 1 FROM ${table} WHERE dataset_revision_id=$1 AND external_id=$2`,[datasetRevisionId,proposal.rows[0]!.record_external_id]);if(!incorporated.rowCount)throw new Error("The published revision does not contain the corrected controlled record.");await client.query("UPDATE service_correction_proposals SET verification_status='published',reviewer_id=$1,dataset_revision_id=$2,published_at=now() WHERE id=$3",[actorId,datasetRevisionId,proposalId]);await audit(client,actorId,"correction.published_revision_linked","service_correction",proposalId,{datasetRevisionId,externalVersion:revision.rows[0].external_version});return{id:proposalId,status:"published",datasetRevisionId};});}

export async function setNotificationPreference(actorId:string,participantId:string,input:{channel:string;category:string;wording:string;enabled:boolean;quietHours?:unknown}){const env=getEnvironment();if(input.channel!=="in_app"&&input.enabled&&(env.EXTERNAL_NOTIFICATIONS_ENABLED!=="true"||env.MAIL_SENDING_ENABLED!=="true"))throw new Error("External notification delivery is disabled pending credentials and approval.");return transaction(async(client)=>{const id=randomUUID();await client.query(`INSERT INTO pilot_notification_preferences (id,participant_id,channel,category,wording,enabled,quiet_hours) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(participant_id,channel,category) DO UPDATE SET wording=$5,enabled=$6,quiet_hours=$7,updated_at=now()`,[id,participantId,input.channel,input.category,input.wording,input.enabled,json(input.quietHours??{})]);await audit(client,actorId,"pilot.notification_preference_changed","pilot_participant",participantId,{channel:input.channel,category:input.category,wording:input.wording,enabled:input.enabled});return{participantId,channel:input.channel,category:input.category,enabled:input.enabled,deliveryAttempted:false};});}

export async function createCostModel(actorId:string,input:{name:string;scenario:string;currency:string}){return transaction(async client=>{const id=randomUUID();await client.query("INSERT INTO operating_cost_models (id,name,scenario,currency,created_by) VALUES ($1,$2,$3,$4,$5)",[id,input.name,input.scenario,input.currency,actorId]);await audit(client,actorId,"cost_model.created","cost_model",id,{scenario:input.scenario,currency:input.currency});return{id};});}
export async function addCostItem(actorId:string,modelId:string,input:{category:string;item:string;quantity:number;unitCost:number;frequency:"one_off"|"monthly"|"quarterly"|"annual";source:string;sourceDate:string;confidence:string;notes:string}){return transaction(async client=>{const id=randomUUID();await client.query("INSERT INTO operating_cost_items (id,model_id,category,item,quantity,unit_cost,frequency,source,source_date,confidence,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",[id,modelId,input.category,input.item,input.quantity,input.unitCost,input.frequency,input.source,input.sourceDate,input.confidence,input.notes]);await audit(client,actorId,"cost_model.item_added","cost_item",id,{modelId,category:input.category,frequency:input.frequency});return{id,annualisedCost:annualisedCost(input.quantity,input.unitCost,input.frequency)};});}
export async function costModel(modelId:string){const [model,items]=await Promise.all([getPool().query("SELECT * FROM operating_cost_models WHERE id=$1",[modelId]),getPool().query<{quantity:string;unit_cost:string;frequency:"one_off"|"monthly"|"quarterly"|"annual"}>("SELECT * FROM operating_cost_items WHERE model_id=$1 ORDER BY category,item",[modelId])]);if(!model.rowCount)return null;return{...model.rows[0],items:items.rows.map(row=>({...row,annualised_cost:annualisedCost(Number(row.quantity),Number(row.unit_cost),row.frequency)})),annualisedTotal:items.rows.reduce((sum,row)=>sum+annualisedCost(Number(row.quantity),Number(row.unit_cost),row.frequency),0)};}

const checklistCategories=["security","privacy","safeguarding","accessibility","data_verification","legal_content","infrastructure","backup","restore","authentication","encryption","evidence","consent","support","incident_response","monitoring","insurance","governance","communications","partner_readiness"];
export async function createLaunchChecklist(actorId:string,input:{name:string;environment:string;releaseVersion?:string}){return transaction(async(client)=>{const id=randomUUID();await client.query("INSERT INTO launch_checklists (id,name,environment,release_version,created_by) VALUES ($1,$2,$3,$4,$5)",[id,input.name,input.environment,input.releaseVersion??null,actorId]);for(const category of checklistCategories)await client.query("INSERT INTO launch_checklist_items (id,checklist_id,category,title,risk,blocking_effect) VALUES ($1,$2,$3,$4,'critical','blocks_activation')",[randomUUID(),id,category,`${category.replaceAll("_"," ")} readiness`]);await audit(client,actorId,"launch_checklist.created","launch_checklist",id,{environment:input.environment});return{id,status:"draft",itemCount:checklistCategories.length};});}
export async function checklistStatus(checklistId:string){const [checklist,items]=await Promise.all([getPool().query("SELECT * FROM launch_checklists WHERE id=$1",[checklistId]),getPool().query("SELECT * FROM launch_checklist_items WHERE checklist_id=$1 ORDER BY category",[checklistId])]);if(!checklist.rowCount)return null;const blockers=items.rows.filter(item=>item.blocking_effect==="blocks_activation"&&item.status!=="complete"&&item.status!=="not_applicable");return{...checklist.rows[0],items:items.rows,ready:blockers.length===0,blockers:blockers.map(item=>item.title)};}

export async function createRelease(actorId:string,input:Record<string,unknown>){return transaction(async client=>{const id=randomUUID();await client.query(`INSERT INTO operational_releases (id,release_version,commit_sha,dataset_revision,migration_level,environment,checklist_id,release_owner_id,rollback_owner_id,release_notes,rollback_version) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,input.releaseVersion,input.commitSha,input.datasetRevision,input.migrationLevel,input.environment,input.checklistId??null,input.releaseOwnerId??null,input.rollbackOwnerId??null,input.releaseNotes,input.rollbackVersion??null]);await audit(client,actorId,"release.record_created","release",id,{releaseVersion:input.releaseVersion,environment:input.environment});return{id,status:"draft",deployed:false};});}

export async function assignOperationalRole(actorId:string,input:{userId:string;role:OperationalRole;region?:string;pilotId?:string;expiresAt?:string}){return transaction(async client=>{const id=randomUUID();await client.query("INSERT INTO operational_role_assignments (id,user_id,role,region,pilot_id,status,approved_by,approved_at,expires_at) VALUES ($1,$2,$3,$4,$5,'active',$6,now(),$7)",[id,input.userId,input.role,input.region??null,input.pilotId??null,actorId,input.expiresAt??null]);await audit(client,actorId,"operational_role.assigned","operational_role",id,{subjectUserId:input.userId,role:input.role,region:input.region??null,pilotId:input.pilotId??null});return{id,status:"active"};});}
export async function releasePreflight(releaseId:string){const release=await getPool().query("SELECT * FROM operational_releases WHERE id=$1",[releaseId]);if(!release.rowCount)return null;const row=release.rows[0],blockers:string[]=[];if(row.environment==="production")blockers.push("Production deployment is not authorised by this workflow.");if(!row.release_owner_id)blockers.push("Release owner is missing.");if(!row.rollback_owner_id)blockers.push("Rollback owner is missing.");if(!row.rollback_version)blockers.push("Rollback version is missing.");if(row.checklist_id){const status=await checklistStatus(row.checklist_id);if(!status?.ready)blockers.push(...(status?.blockers??["Launch checklist is missing."]));}else blockers.push("Launch checklist is missing.");const open=await getPool().query<{id:string}>("SELECT id FROM operational_release_gates WHERE status<>'closed' AND (id='PHASE5-LAUNCH-001' OR $1<>'production')",[row.environment]);blockers.push(...open.rows.map(item=>`${item.id} is not closed.`));return{releaseId,ready:blockers.length===0,blockers:[...new Set(blockers)],dryRun:true,deployed:false};}
export async function prepareRollback(actorId:string,releaseId:string,backupReference:string){return transaction(async(client)=>{const release=await client.query("SELECT rollback_version FROM operational_releases WHERE id=$1 FOR UPDATE",[releaseId]);if(!release.rowCount||!release.rows[0].rollback_version)throw new Error("A rollback version must be recorded first.");await client.query("UPDATE operational_releases SET status='rollback_prepared',backup_reference=$1,rollback_prepared_at=now() WHERE id=$2",[backupReference,releaseId]);await audit(client,actorId,"release.rollback_prepared","release",releaseId,{backupReference});return{id:releaseId,status:"rollback_prepared",executed:false};});}

export async function commissionerReport(actorId:string,pilotId:string,periodStart:string,periodEnd:string,minimum=5){const [outcomes,events,feedback,incidents]=await Promise.all([getPool().query<{label:string;count:number}>("SELECT outcome_type label,count(*)::int count FROM pilot_outcomes WHERE pilot_id=$1 AND occurred_on BETWEEN $2 AND $3 GROUP BY outcome_type",[pilotId,periodStart,periodEnd]),getPool().query<{label:string;count:number}>("SELECT event_type label,sum(event_count)::int count FROM operational_analytics_events WHERE pilot_id=$1 AND occurred_on BETWEEN $2 AND $3 GROUP BY event_type",[pilotId,periodStart,periodEnd]),getPool().query<{label:string;count:number}>("SELECT category label,count(*)::int count FROM pilot_feedback f JOIN pilot_cohorts c ON c.id=f.cohort_id WHERE c.pilot_id=$1 AND f.created_at::date BETWEEN $2 AND $3 GROUP BY category",[pilotId,periodStart,periodEnd]),getPool().query<{label:string;count:number}>("SELECT severity label,count(*)::int count FROM operational_incidents WHERE detected_at::date BETWEEN $1 AND $2 GROUP BY severity",[periodStart,periodEnd])]);const data={actual:{outcomes:suppressSmallCells(outcomes.rows,minimum),events:suppressSmallCells(events.rows,minimum),feedback:suppressSmallCells(feedback.rows,minimum),incidents:suppressSmallCells(incidents.rows,minimum)},targets:[],assumptions:[],projections:[],unmeasured:["Long-term housing stability","Outcomes not voluntarily reported"]};const limitations=["Counts below the minimum group size are suppressed.","Optional outcome reporting means totals are incomplete."];const id=randomUUID();await getPool().query("INSERT INTO commissioner_reports (id,pilot_id,period_start,period_end,minimum_group_size,generated_by,report_data,limitations) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)",[id,pilotId,periodStart,periodEnd,minimum,actorId,json(data),json(limitations)]);return{id,data,privacy:{minimumGroupSize:minimum,directIdentifiers:false}};}
