import Link from "next/link";
import { notFound } from "next/navigation";
import { CaseAddForm } from "@/components/case-add-form";
import { CaseNav } from "@/components/case-nav";
import { CaseWorkflowForm } from "@/components/case-workflow-form";
import { currentSession } from "@/server/auth-cookie";
import { getCase } from "@/server/casework";

const copy={timeline:["Timeline","Record what happened in your own words. Suggested entries are never saved without approval."],applications:["Applications and referrals","Every submission keeps a manifest of the fields and evidence selected."],duties:["Council duties","These records organise what the council says. They do not decide that a legal duty exists."],evidence:["Evidence vault","Encrypted metadata can be organised now. File upload and download are blocked until secure storage and malware scanning pass EVIDENCE-001."],documents:["Documents","Prepare versioned letters and review every word before copying, printing, or exporting."],deadlines:["Deadlines","Confirmed, estimated, suggested, and user-created dates are labelled differently."],people:["People helping me","Friends, family, advisers and other trusted people only see specifically granted information."],sharing:["Sharing and consent","Review recipients, purposes, data, expiry, and revoke future access immediately."],suitability:["Accommodation suitability","Record factual concerns about safety, location, access, condition, household needs and support."],complaints:["Complaints and escalation","A complaint is not a substitute for a statutory review or urgent legal advice."],reviews:["Statutory review preparation","Record the written decision, date, reasons, evidence and any uncertainty about the deadline."],export:["Export case","Choose exactly what to include. Sensitive categories are excluded by default."]} as const;
type Section=keyof typeof copy;
type CaseData={id:string;reference:string;events:Array<{id:string;event_at:Date|string;event_type:string;description:string;privacy_classification:string}>;deadlines:Array<{id:string;title:string;due_at:Date|string;deadline_status:string;confidence:string}>;applications:Array<{id:string;kind:string;destination:string;status:string}>;duties:Array<{id:string;duty_type:string;legal_status:string}>;evidence:Array<{id:string;title:string;category:string;sensitivity:string;storage_state:string}>;people:Array<{id:string}>};
export async function CaseSection({caseId,section}:{caseId:string;section:Section}){const session=await currentSession();if(!session)return <><h1>Sign in required</h1><p>This private case section cannot be shown without a valid session.</p></>;const data=await getCase(session,caseId);if(!data)notFound();const [title,intro]=copy[section],addable=["timeline","deadlines","applications","duties","evidence"] as const,workflows=["suitability","complaints","reviews"] as const;return <><p className="meta"><Link href={`/case/${caseId}`}>{data.reference}</Link></p><h1>{title}</h1><p className="lede">{intro}</p><CaseNav caseId={caseId}/>{addable.includes(section as typeof addable[number])&&<CaseAddForm caseId={caseId} kind={section as typeof addable[number]}/>} {workflows.includes(section as typeof workflows[number])&&<CaseWorkflowForm caseId={caseId} kind={section as typeof workflows[number]}/>}<SectionBody section={section} data={data as CaseData}/></>}
function SectionBody({section,data}:{section:Section;data:CaseData}){if(section==="timeline")return <ul className="timeline">{data.events.map(item=><li key={item.id}><strong>{new Date(item.event_at).toLocaleString("en-GB")} · {item.event_type.replaceAll("_"," ")}</strong><p>{item.description}</p><span className="meta">{item.privacy_classification}</span></li>)}</ul>;if(section==="deadlines")return <ul className="service-list">{data.deadlines.map(item=><li className="service-card" key={item.id}><h2>{item.title}</h2><p>{new Date(item.due_at).toLocaleString("en-GB")}</p><p><span className="status">{item.deadline_status.replaceAll("_"," ")}</span> Confidence: {item.confidence}</p></li>)}</ul>;if(section==="applications")return <ul className="service-list">{data.applications.map(item=><li className="service-card" key={item.id}><h2>{item.kind}</h2><p>{item.destination}</p><span className="status">{item.status.replaceAll("_"," ")}</span></li>)}</ul>;if(section==="duties")return <><p className="callout">Use “appears to be considering” unless a written decision confirms the duty.</p><ul className="service-list">{data.duties.map(item=><li className="service-card" key={item.id}><h2>{item.duty_type}</h2><p>{item.legal_status.replaceAll("_"," ")}</p></li>)}</ul></>;if(section==="evidence")return <><p className="callout"><strong>File storage is off.</strong> No file bytes or object-storage links are accepted while EVIDENCE-001 is open.</p><ul className="service-list">{data.evidence.map(item=><li className="service-card" key={item.id}><h2>{item.title}</h2><p>{item.category} · {item.sensitivity}</p><span className="status">{item.storage_state.replaceAll("_"," ")}</span></li>)}</ul></>;if(section==="people"||section==="sharing")return <><p>Active and historical grants: {data.people.length}</p><p><Link href="/advocate/invitations">Invite someone with selected permissions</Link> · <Link href="/consent">Open consent centre</Link></p></>;if(section==="export")return <><div className="review-panel"><h2>Export preview</h2><p>Case reference and summary are selected. Evidence, health, abuse, immigration, criminal-justice and children’s data remain excluded until individually selected.</p></div><p><Link href={`/api/v1/cases/${data.id}/export?format=json`}>Download structured case summary</Link> · <Link href={`/api/v1/cases/${data.id}/export?format=pdf`}>Download printable PDF</Link></p></>;return <div className="review-panel"><h2>Controlled workflow</h2><p>This workspace stores drafts, decisions and provenance. It never sends externally or treats a draft as a legal determination.</p></div>}
