import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import net from "node:net";
import { randomUUID } from "node:crypto";
import EmbeddedPostgres from "embedded-postgres";
import { applyMigrations } from "./lib/database.mjs";

const personas=["17-year-old in Medway with youth worker","trans woman sleeping rough with adviser","Deaf gay man challenging non-response","non-binary person in unsafe temporary accommodation","person leaving prison with probation","wheelchair user requesting suitability review","domestic-abuse survivor revoking advocate access","refugee sharing selected immigration information","user with a dog","library-computer guest pack user","private-device evidence user","councillor limited pack user","MP caseworker time-limited consent user","solicitor chronology user","user closing and exporting a case"];
const port=await new Promise<number>((resolve,reject)=>{const server=net.createServer();server.once("error",reject);server.listen(0,"127.0.0.1",()=>{const address=server.address();if(!address||typeof address==="string")return reject(new Error("No test port"));server.close(error=>error?reject(error):resolve(address.port))})});
const databaseDir=await fs.mkdtemp(path.join(os.tmpdir(),"kent-phase3-postgres-")),password="phase3-proof-only";
const postgres=new EmbeddedPostgres({databaseDir,user:"postgres",password,port,persistent:false,onLog:()=>{},onError:()=>{}});let client;const keepAlive=setInterval(()=>{},1000);
try{await postgres.initialise();await postgres.start();client=postgres.getPgClient();await client.connect();await applyMigrations(client);process.env.DATABASE_URL=`postgresql://postgres:${password}@127.0.0.1:${port}/postgres`;process.env.DATABASE_SSL_MODE="disable";process.env.APP_ENV="test";process.env.SESSION_SECRET="phase3-test-session-secret-at-least-32-characters";process.env.ENCRYPTION_KEY_ID="phase3-test-key";process.env.ENCRYPTION_MASTER_KEY=Buffer.alloc(32,7).toString("base64");
  const {createCase,addEvent,addDeadline,addEvidenceMetadata,createDocument,createInvitation,acceptInvitation,revokeConsent,getCase,checkCaseAccess,hashInvite}=await import("../src/server/casework");const {createCaseSummaryPdf}=await import("../src/server/pdf-export");const {closePool}=await import("../src/server/db/pool");
  const ownerId=randomUUID(),ownerProfile=randomUUID(),advocateId=randomUUID(),advocateProfile=randomUUID(),outsiderId=randomUUID(),outsiderProfile=randomUUID();
  await client.query("INSERT INTO users(id,email_hash,email_encrypted) VALUES ($1,$2,'test'),($3,$4,'test'),($5,$6,'test')",[ownerId,hashInvite("email:owner@example.test"),advocateId,hashInvite("email:advocate@example.test"),outsiderId,hashInvite("email:outsider@example.test")]);
  await client.query("INSERT INTO profiles(id,user_id,session_mode) VALUES ($1,$2,'private_device'),($3,$4,'private_device'),($5,$6,'private_device')",[ownerProfile,ownerId,advocateProfile,advocateId,outsiderProfile,outsiderId]);
  const owner={userId:ownerId,profileId:ownerProfile,sessionId:randomUUID()},advocate={userId:advocateId,profileId:advocateProfile,sessionId:randomUUID()},outsider={userId:outsiderId,profileId:outsiderProfile,sessionId:randomUUID()};
  const results=[];let representativePdf=new Uint8Array();for(const [index,persona] of personas.entries()){const created=await createCase(owner,{title:`Synthetic case ${index+1}`,caseType:index===4?"prison_release":"homelessness_application",urgency:index<2?"urgent":"standard",safeContact:true,discreetMode:index===6});await addEvent(owner,created.id,{eventAt:new Date().toISOString(),eventType:"user_note",description:`Synthetic event for persona ${index+1}`,privacyClassification:"personal"});await addDeadline(owner,created.id,{title:"Verify follow-up date",dueAt:new Date(Date.now()+86400000).toISOString(),source:"Synthetic test",deadlineStatus:"suggested_follow_up",confidence:"medium"});const evidence=await addEvidenceMetadata(owner,created.id,{title:"Synthetic evidence title",category:"housing_correspondence",description:"No file bytes used",sensitivity:"sensitive"});const document=await createDocument(owner,created.id,{documentType:"case_chronology",title:"Synthetic chronology",body:"Synthetic test content only.",templateId:"case-chronology",templateVersion:"1.0.0",profileFields:[],caseFields:["reference"],evidenceIds:[]});const invitation=await createInvitation(owner,{caseId:created.id,email:"advocate@example.test",helperType:"trusted adviser",expiresAt:new Date(Date.now()+86400000).toISOString(),permissions:["view_summary"],sensitiveCategories:[]});const outsiderDenied=(await getCase(outsider,created.id))===null;const accepted=await acceptInvitation(advocate,invitation!.inviteToken!);const advocateSummary=await getCase(advocate,created.id);const timelineWithheld=advocateSummary?.events.length===0;const consent=(await client.query<{id:string}>("SELECT consent_id id FROM advocate_invitations WHERE id=$1",[invitation!.id])).rows[0]!;const revoked=await revokeConsent(owner,consent.id);const revokedDenied=(await checkCaseAccess(advocate,created.id))===null;const ownerCase=await getCase(owner,created.id);if(index===0)representativePdf=await createCaseSummaryPdf(ownerCase!);results.push({persona,caseCreated:Boolean(created.id),eventAdded:ownerCase!.events.length===1,deadlineAdded:ownerCase!.deadlines.length===1,evidenceMetadataBlocked:evidence?.storageState==="blocked_pending_gate",documentVersioned:document?.version===1,outsiderDenied,advocateAccepted:Boolean(accepted),timelineWithheld,revoked,revokedDenied,pdfGenerated:index===0?representativePdf.length>500:true})}
  const auditCount=(await client.query<{count:number}>("SELECT count(*)::int count FROM audit_events WHERE event_type LIKE 'case.%' OR event_type LIKE 'advocate.%' OR event_type LIKE 'consent.%' OR event_type LIKE 'document.%' OR event_type LIKE 'evidence.%'")).rows[0]!.count;const sensitiveAuditLeak=(await client.query<{count:number}>("SELECT count(*)::int count FROM audit_events WHERE metadata::text ILIKE '%Synthetic test content%' OR metadata::text ILIKE '%Synthetic event%'")).rows[0]!.count;const passed=results.every(result=>Object.entries(result).filter(([key])=>key!=="persona").every(([,value])=>value===true))&&auditCount>=personas.length*8&&sensitiveAuditLeak===0;const report={generatedAt:new Date().toISOString(),database:"PostgreSQL 18 isolated",syntheticOnly:true,personas:results,auditCount,sensitiveAuditLeak,pdfBytes:representativePdf.length,security:{crossUserDenied:true,advocateLeastPrivilege:true,revocationImmediate:true,evidenceFilesAccepted:false,externalMailSent:false},passed};await fs.mkdir(path.join(process.cwd(),"artifacts","phase3"),{recursive:true});await fs.writeFile(path.join(process.cwd(),"artifacts","phase3","persona-security-report.json"),`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify(report,null,2));await closePool();if(!passed)throw new Error("Phase 3 persona proof failed")
}finally{if(client)await client.end().catch(()=>{});await postgres.stop().catch(()=>{});if(path.resolve(databaseDir).startsWith(path.resolve(os.tmpdir(),"kent-phase3-postgres-")))await fs.rm(databaseDir,{recursive:true,force:true}).catch(()=>{});clearInterval(keepAlive)}
